#!/bin/bash

# Health API テスト用curlコマンド集
# 使用方法: ./curl_examples.sh

BASE_URL="http://localhost:3000"
AUTH_HEADER="Authorization: Basic YWRtaW46cGFzc3dvcmQ="

echo "=== Health API テストコマンド集 ==="
echo ""

echo "1. GET /api/v1/health (成功例)"
echo "curl -X GET \"$BASE_URL/api/v1/health?message=hello\" \\"
echo "  -H \"$AUTH_HEADER\""
echo ""

echo "2. GET /api/v1/health (エラー例 - パラメータなし)"
echo "curl -X GET \"$BASE_URL/api/v1/health\" \\"
echo "  -H \"$AUTH_HEADER\""
echo ""

echo "3. POST /api/v1/health (基本データ)"
echo "curl -X POST \"$BASE_URL/api/v1/health\" \\"
echo "  -H \"$AUTH_HEADER\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"health\": {"
echo "      \"id\": \"123\","
echo "      \"data\": \"test data\","
echo "      \"message\": \"health check\""
echo "    }"
echo "  }'"
echo ""

echo "4. POST /api/v1/health (複雑なデータ)"
echo "curl -X POST \"$BASE_URL/api/v1/health\" \\"
echo "  -H \"$AUTH_HEADER\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"health\": {"
echo "      \"id\": \"monitoring_001\","
echo "      \"data\": \"System monitoring data\","
echo "      \"message\": \"Daily health check\","
echo "      \"settings\": {"
echo "        \"enabled\": true,"
echo "        \"timeout\": 60,"
echo "        \"retry_count\": 5"
echo "      },"
echo "      \"metadata\": {"
echo "        \"version\": \"2.1.0\","
echo "        \"created_at\": \"2024-01-01T12:00:00Z\","
echo "        \"tags\": [\"monitoring\", \"production\"]"
echo "      },"
echo "      \"tags\": [\"critical\", \"daily\"],"
echo "      \"nested_data\": ["
echo "        {"
echo "          \"name\": \"cpu_usage\","
echo "          \"value\": 75,"
echo "          \"sub_items\": ["
echo "            { \"id\": 1, \"label\": \"core1\" },"
echo "            { \"id\": 2, \"label\": \"core2\" }"
echo "          ]"
echo "        }"
echo "      ]"
echo "    }"
echo "  }'"
echo ""

echo "5. PUT /api/v1/health (データ更新)"
echo "curl -X PUT \"$BASE_URL/api/v1/health\" \\"
echo "  -H \"$AUTH_HEADER\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"health\": {"
echo "      \"id\": \"123\","
echo "      \"data\": \"updated data\","
echo "      \"settings\": {"
echo "        \"enabled\": false,"
echo "        \"timeout\": 30,"
echo "        \"retry_count\": 3"
echo "      }"
echo "    }"
echo "  }'"
echo ""

echo "6. DELETE /api/v1/health (成功例)"
echo "curl -X DELETE \"$BASE_URL/api/v1/health?id=123\" \\"
echo "  -H \"$AUTH_HEADER\""
echo ""

echo "7. DELETE /api/v1/health (エラー例 - パラメータなし)"
echo "curl -X DELETE \"$BASE_URL/api/v1/health\" \\"
echo "  -H \"$AUTH_HEADER\""
echo ""

echo "8. 認証エラー (認証なし)"
echo "curl -X GET \"$BASE_URL/api/v1/health?message=hello\""
echo ""

echo "9. JSON形式エラー (不正なJSON)"
echo "curl -X POST \"$BASE_URL/api/v1/health\" \\"
echo "  -H \"$AUTH_HEADER\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{ invalid json }'"
echo ""

echo "10. スキーマバリデーションエラー (不正な値)"
echo "curl -X POST \"$BASE_URL/api/v1/health\" \\"
echo "  -H \"$AUTH_HEADER\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"health\": {"
echo "      \"id\": \"123\","
echo "      \"settings\": {"
echo "        \"timeout\": 999"
echo "      }"
echo "    }"
echo "  }'"
echo ""

echo "=== テスト実行方法 ==="
echo "1. サーバーを起動: rails server"
echo "2. 上記のコマンドをコピー&ペーストして実行"
echo "3. レスポンスを確認"
echo ""
echo "=== 期待される結果 ==="
echo "- 成功時: HTTP 200 OK + JSONレスポンス"
echo "- エラー時: HTTP 400 Bad Request + エラーJSON"
echo "- 認証エラー: HTTP 401 Unauthorized" 